PROGRAM PrintHello(INPUT, OUTPUT);
USES
  DOS;
BEGIN
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('Hello World!');
  WRITELN(GetEnv('REQUEST_METHOD'));
  WRITELN(GetEnv('HTTP_HOST'));
  WRITELN(GetEnv('QUERY_STRING'));
  WRITELN(GetEnv('CONTENT_LENGTH'));
  WRITELN(GetEnv('HTTP_USER_AGENT'))
END.
